name: my portofolio

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v3.1.1 # Disarankan versi stabil jika menggunakan server-dir
      with:
        server: ftp.zakkal.my.id
        # Ganti dengan username login utama DirectAdmin Anda (misal: evo / zakkal)
        username: myportofolio@zakkal.my.id
        # Ganti dengan password login utama DirectAdmin Anda
        password: myportofolio
        server-dir: /domains/my.portofolio.zakkal.my.id/public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
