name: my portofolio

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.zakkal.my.id
        username: myportofolio@zakkal.my.id
        password: myportofolio
        timeout: 1200000
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
